config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/deconnexion', to: 'accueil#logout', as: 'logout'
  get  '/connexion',   to: 'accueil#login', as: 'login'
  post '/connexion',  to: 'accueil#login'

  # get '/demandes',     to: 'demandes#index'
  resources :demandes
  # get '/demande/new',     to: 'demande#new', as: 'demande_new'
  # get '/demande/edit',     to: 'demande#edit', as: 'demande_edit'
  get '/admin/demandes', to: 'admin#index', as: 'admin_demande'
  get '/admin/demandes/valider/:id_demande', to: 'admin#valider', as: 'valider_demande'
  post '/admin/demandes/refuser', to: 'admin#refuser', as: 'refuser_demande'
  get '/admin/demandes/show/:id_demande', to: 'admin#show', as: 'show_demande'
  root to: 'accueil#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/demande.rb
class Demande < ApplicationRecord
  belongs_to :utilisateur
  enum type_conges: {
    conge_paye: 'Congés payés',
    conge_maladie: 'Congés maladie',
    conge_non_paye: 'Congés non payés'
  }
  validates :debut,
    presence: {message: ' du congé obligatoire'}
  validates :fin,
    presence: {message: ' du congé obligatoire'}
  validates :nb_jours,
    presence: {message: ' Obligatoire'},
    numericality: {greater_than: 0,message: ' doit etre supérieur à zéro'},
    numericality: {less_than_or_equal: :diff_fin_debut, message: " doit être inférieur à %{count}"} if :fin_et_debut_valide

  def diff_fin_debut
    (fin - debut).ceil
  end

  def fin_et_debut_valide
    fin && debut && fin > debut
  end

  def nom_type_conges
    Demande.type_conges[type_conges]
  end

  def refuser (motif_refus)
    update acceptee: true,motif_refus: motif_refus
  end

  def valider
    update acceptee: true
  end
end

app/models/utilisateur.rb
class Utilisateur < ApplicationRecord
  has_secure_password
  has_many :demandes
  enum role: {
    admin: 'Administrateur',
    user: 'Utilisateur'
  }
  validates :email,
    presence: true,
    uniqueness: true
  def self.authenticate(email, password)
    me = where(email: email).first
    me && me.authenticate(password)
  end
end

app/controllers/accueil_controller.rb
class AccueilController < ApplicationController
    def login
        if params[:utilisateur]
            email, password = params[:utilisateur][:email], params[:utilisateur][:password]
            user = Utilisateur.authenticate(email, password)

            if user
                session[:user] = user
                if is_admin?
                  redirect_to admin_demande_path
                else
                  redirect_to root_path
                end
            else
                @erreur = "Email ou mot de passe incorrect"
                render :login
            end
        end
    end
    def logout
        session[:user]   = nil
        redirect_to login_path
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index
    @demandes = Demande.where(acceptee: nil);
  end

  def valider
    demande = serviceDemande.get_by_id(params[:id_demande])
    if not demande
      flash[:danger] = "La demande n'existe pas"
    elsif serviceDemande.valider(demande)
      flash[:info] = "Demande acceptée"
    else
      flash[:danger] = "Erreur lors de la validation"
    end

    redirect_to admin_demande_path
  end

  def refuser
    demande = serviceDemande.get_by_id(params[:id_demande])
    if not demande
      flash[:danger] = "La demande n'existe pas"
    elsif serviceDemande.refuser(demande,params[:refus_motif])
      flash[:info] = "Demande refusée"
    else
      flash[:danger] = "Erreur lors de la validation"
    end

    redirect_to admin_demande_path
  end
  def show
    @demande = serviceDemande.get_by_id(params[:id_demande])
  end
  def serviceDemande
    serviceDemande ||= DemandeService.new
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :are_you_in?, except: [:login]
  protect_from_forgery with: :exception
  helper_method 'connected?'

  @project_name = 'Demande congé'

  def connected?
    !session[:user].nil?
  end
  def is_admin?
    connected? && session[:user]['role'] == 'admin'
  end
  def are_you_in?
    redirect_to login_path unless connected?
  end
end

app/controllers/demandes_controller.rb
class DemandesController < ApplicationController
  def index
    @demandes = Demande.where(utilisateur_id: session[:user]['id'] )
  end

  def new
  end

  def create
    # p 'les paramètres reçus', demande_params
    # demande_params << utilisateur_id: session[:user]['id']
    @demande = Demande.new(demande_params.merge(utilisateur_id: session[:user]['id']))
    if @demande.save
      DemandeMailer.new_demande_email(@demande).deliver_later
      redirect_to demandes_path, notice: 'Demande envoyée'
    else
      render new_demande_path
    end
  end

  def demande_params
    params.require(:demande).permit(:debut,:fin,:nb_jours,:type_conges,:motif)
  end
end

app/helpers/accueil_helper.rb
module AccueilHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def list_type_conges
    Demande.type_conges.values
  end
end

app/views/accueil/login.html.erb
<div class="container" style="">
	<div class="row">
    <div class="col-lg-4"></div>

    <div class="col-lg-4">
      <h2 class="text-muted">Se connecter</h2>
      <%= @erreur if @erreur %>
      <%= form_tag do %>
        <div class="form-group">
          <%= text_field :utilisateur, :email, placeholder: 'email', class: 'form-control'%>
          </div>
          <div class="form-group">
            <%= password_field :utilisateur, :password, placeholder: 'mot de passe', class: 'form-control'%>
          </div>
        <div class="form-group">
          <%= submit_tag 'connexion', disable_with: 'connexion en cours...', class: 'btn btn-primary' %>
        </div>
        <% end %>
      </div>

     </div>

    <div class="col-lg-4"></div>
	</div>
</div>

app/views/admin/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="">
      <% flash.each do |key,msg| %>
        <div class="alert alert-<%= key %>">
          <%= msg %>
        </div>
      <% end %>
    </div>
    <div class="">
      <table class="table table-stripped">
        <thead>
          <tr>
            <th>Debut </th>
            <th>Fin </td>
            <th>Nombre de jours </th>
            <th>Type de congé </th>
            <th>Collaborateur </th>
            <th>Actions</th>
          </tr>
        </thead>
        <% @demandes.each do |demande| %>
        <tr>

          <td><%= demande.debut.strftime('%d %B %Y') %></td>
          <td><%= demande.fin.strftime('%d %B %Y') %></td>
          <td><%= demande.nb_jours %></td>
          <td><%= demande.nom_type_conges%></td>
          <td><%= demande.utilisateur.prenom + ' ' +demande.utilisateur.nom%></td>
          <td>
            <%= link_to '', show_demande_path(demande.id), class: 'fa fa-eye' %>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>
<div class="modal fade" id="refus-popup" tabindex="-1" role="dialog" aria-labelledby="myLabel" aria-hidden="true">
</div>

app/views/admin/show.html.erb
<div class="row">
  <div class="">
    <%= link_to 'Retour à la liste', admin_demande_path, class: 'btn btn-default' %>
  </div>
  <div class="col-md-12">
    <h6>Détails de la demande</h6>
    <div class="">
      <strong>Par: </strong>
      <%= @demande.utilisateur.prenom + ' ' + @demande.utilisateur.nom %>
    </div>
    <div class="  ">
      <strong>Début: </strong>
      <%= @demande.debut.strftime('%d %B %Y') %>
    </div>
    <div class="">
      <strong>Fin: </strong>
      <%= @demande.fin.strftime('%d %B %Y') %>
    </div>
    <div class="  ">
      <strong>Nombre de jours: </strong>
      <%= @demande.nb_jours %>
    </div>
    <div class="">
      <strong>Type de congé: </strong>
      <%= @demande.nom_type_conges %>
    </div>
    <%= form_tag refuser_demande_path, method: :post, class: "form-inline hide-default", id: 'refusForm' do %>
      <%= text_field_tag(
          :refus_motif,
          params[:refus_motif],
          placeholder: "Motif nak",
          class: "form-control input-lg"
      ) %>
      <%= hidden_field_tag(
          :id_demande,
          params[:id_demande]
      ) %>

      <%= submit_tag(
          "Valider",
          class: 'btn btn-default'
      ) %>
    <% end %>
      <!-- <div class="form-group" >
        <label for="">Motif: </label>
        <input type="text" id="inputMotif" class="input-lg form-control" name="refus_motif" value="" placeholder="Motif du refus">
        <input type="hidden" name="id_demande" value="<%= @demande.id %>">
      </div> -->
      <!-- <div class="form-group">
        <button type="submit" class="btn btn-default">
          Envoyer
        </button>
      </div> -->

    <div class="" id="btn_option" >
        <%= link_to  'Valider', valider_demande_path(@demande.id), class: "btn btn-info" %>
        <%= link_to 'Refuser', refuser_demande_path(@demande.id), class: "btn btn-warning", :onclick => 'refus_click(event)' %>
    </div>
  </div>
</div>
<script type="text/javascript">
  function refus_click(ev) {
    ev.preventDefault()
    var formRefus = $("#refusForm");
    var btnOption = $("#btn_option");
    formRefus.fadeIn();
    btnOption.fadeOut();

  }
</script>

app/views/demandes/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="">
      <%= link_to 'Nouvelle demande', new_demande_path, class: 'btn btn-success' %>
    </div>
    <div class="">
      <table class="table table-stripped">
        <thead>
          <tr>
            <th>Debut </th>
            <th>Fin </td>
            <th>Nombre de jours </th>
            <th>Type de congé </th>
            <th>Actions</th>
          </tr>
        </thead>
        <% @demandes.each do |demande| %>
        <tr>

          <td><%= demande.debut.strftime('%d %B %Y') %></td>
          <td><%= demande.fin.strftime('%d %B %Y') %></td>
          <td><%= demande.nb_jours %></td>
          <td><%= demande.type_conges %></td>
          <td><%= link_to 'Editer', demandes_path, class: 'glyphicon glyphicon-pencil' %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/demandes/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h5>Demande de congé</h5>
    <div class="errors">
      <ul class="">
        <% if @demande and @demande.errors %>
          <% @demande.errors.full_messages.each do |erreur| %>
          <li class="warning"><%= erreur %></li>
          <% end %>
        <% end %>

      </ul>
    </div>
    <%=  form_with(model: Demande, local: true) do |form| %>
      <div class="form-group">
        <%= form.label :debut  %>
        <%= form.date_field :debut, id: :debut_conge , class: 'form-control'%>
      </div>
      <div class="form-group">
        <%= form.label :fin %>
        <%= form.date_field :fin, id: :fin_conge, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :nombre_de_jours %>
        <%= form.number_field :nb_jours, id: :nb_jours, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :type_de_congé %>
        <%= form.select :type_conges,list_type_conges, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :motif  %>
        <%= form.text_field :motif, id: :motif, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.submit 'Envoyer', class: ' btn btn-primary'  %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Neticonges</title>
    <%= csrf_meta_tags %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js" charset="utf-8"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="menu">
          <%= link_to 'Accueil', root_path %>
          <% if connected? %>
          <%= link_to 'Demandes', demandes_path %>
            <%= link_to 'Déconnexion', logout_path %>
          <% else %>
            <%= link_to 'Connexion', login_path %>
          <% end %>
        </div>
      </div>
      <div class="content">
        <%= yield %>
      </div>
      <div class="footer"></div>
    </div>
  </body>
</html>